/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.nkwa.pay.pay_sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.nkwa.pay.pay_sdk.utils.HasSecurity;
import org.nkwa.pay.pay_sdk.utils.SpeakeasyMetadata;
import org.nkwa.pay.pay_sdk.utils.Utils;

public class Security implements HasSecurity {

    @SpeakeasyMetadata("security:scheme=true,type=apiKey,subtype=header,name=X-API-Key")
    private String apiKeyAuth;

    @JsonCreator
    public Security(
            String apiKeyAuth) {
        Utils.checkNotNull(apiKeyAuth, "apiKeyAuth");
        this.apiKeyAuth = apiKeyAuth;
    }

    @JsonIgnore
    public String apiKeyAuth() {
        return apiKeyAuth;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public Security withApiKeyAuth(String apiKeyAuth) {
        Utils.checkNotNull(apiKeyAuth, "apiKeyAuth");
        this.apiKeyAuth = apiKeyAuth;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Security other = (Security) o;
        return 
            Objects.deepEquals(this.apiKeyAuth, other.apiKeyAuth);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            apiKeyAuth);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Security.class,
                "apiKeyAuth", apiKeyAuth);
    }
    
    public final static class Builder {
 
        private String apiKeyAuth;
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder apiKeyAuth(String apiKeyAuth) {
            Utils.checkNotNull(apiKeyAuth, "apiKeyAuth");
            this.apiKeyAuth = apiKeyAuth;
            return this;
        }
        
        public Security build() {
            return new Security(
                apiKeyAuth);
        }
    }
}
