/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.nkwa.pay.pay_sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum TelecomOperator {
    MTN("mtn"),
    ORANGE("orange");

    @JsonValue
    private final String value;

    private TelecomOperator(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<TelecomOperator> fromValue(String value) {
        for (TelecomOperator o: TelecomOperator.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

