/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.github.nkwa.pay_sdk.models.operations;

import io.github.nkwa.pay_sdk.models.components.PaymentRequest;
import io.github.nkwa.pay_sdk.utils.Utils;
import java.lang.Exception;

public class PostCollectRequestBuilder {

    private PaymentRequest request;
    private final SDKMethodInterfaces.MethodCallPostCollect sdk;

    public PostCollectRequestBuilder(SDKMethodInterfaces.MethodCallPostCollect sdk) {
        this.sdk = sdk;
    }

    public PostCollectRequestBuilder request(PaymentRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public PostCollectResponse call() throws Exception {

        return sdk.collect(
            request);
    }
}
