/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.nkwa.pay.pay_sdk.models.operations;

import java.lang.Exception;

public class GetAvailabilityRequestBuilder {

    private final SDKMethodInterfaces.MethodCallGetAvailability sdk;

    public GetAvailabilityRequestBuilder(SDKMethodInterfaces.MethodCallGetAvailability sdk) {
        this.sdk = sdk;
    }

    public GetAvailabilityResponse call() throws Exception {

        return sdk.checkDirect();
    }
}
