/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.nkwa.pay.pay_sdk.models.operations;

import java.lang.Exception;
import java.lang.String;
import org.nkwa.pay.pay_sdk.utils.Utils;

public class GetPaymentsIdRequestBuilder {

    private String id;
    private final SDKMethodInterfaces.MethodCallGetPaymentsId sdk;

    public GetPaymentsIdRequestBuilder(SDKMethodInterfaces.MethodCallGetPaymentsId sdk) {
        this.sdk = sdk;
    }

    public GetPaymentsIdRequestBuilder id(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public GetPaymentsIdResponse call() throws Exception {

        return sdk.get(
            id);
    }
}
