/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.nkwa.pay.pay_sdk.models.operations;

import java.lang.Exception;
import org.nkwa.pay.pay_sdk.models.components.PaymentRequest;
import org.nkwa.pay.pay_sdk.utils.Utils;

public class PostDisburseRequestBuilder {

    private PaymentRequest request;
    private final SDKMethodInterfaces.MethodCallPostDisburse sdk;

    public PostDisburseRequestBuilder(SDKMethodInterfaces.MethodCallPostDisburse sdk) {
        this.sdk = sdk;
    }

    public PostDisburseRequestBuilder request(PaymentRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public PostDisburseResponse call() throws Exception {

        return sdk.disburse(
            request);
    }
}
