/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.nkwa.pay.pay_sdk.models.operations;

import java.lang.Exception;
import java.lang.String;
import org.nkwa.pay.pay_sdk.models.components.PaymentRequest;

public class SDKMethodInterfaces {

    public interface MethodCallGetPaymentsId {
        GetPaymentsIdResponse get(
            String id) throws Exception;
    }

    public interface MethodCallPostCollect {
        PostCollectResponse collect(
            PaymentRequest request) throws Exception;
    }

    public interface MethodCallPostDisburse {
        PostDisburseResponse disburse(
            PaymentRequest request) throws Exception;
    }

    public interface MethodCallGetAvailability {
        GetAvailabilityResponse checkDirect() throws Exception;
    }
}
