/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.github.nkwa.pay_sdk;
public class Operators {

    private final SDKConfiguration sdkConfiguration;
    private final Availability availability;

    Operators(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.availability = new Availability(this.sdkConfiguration);
    }

    public final Availability availability() {
        return availability;
    }
}
