/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.github.nkwa.pay_sdk.utils;

/**
 * Implemented by classes that have security annotations on fields.
 **/
public interface HasSecurity {
}